[package]
name = "nfs-mount"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
xdr-codec = { path = "../xdr-codec" }
onc-rpc = { path = "../onc-rpc" }
nfs4-types = { path = "../nfs4-types" }
nfs4-client = { path = "../nfs4-client" }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
